// GENERAL
export const SET_LOADING_VALUE = 'SET_LOADING_VALUE'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'

// AUTH
export const LOGOUT_USER = 'LOGOUT_USER'
export const SET_USER_DATA = 'SET_USER_DATA'

// CATEGORY
export const SET_CATEGORIES_DATA = 'SET_CATEGORIES_DATA'
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS'

// SUB
export const SET_SUB_DATA = 'SET_SUB_DATA'
export const SET_CURRENT_SUB = 'SET_CURRENT_SUB'
export const SET_CATEGORY_SUBS = 'SET_CATEGORY_SUBS'
export const SET_SUB_PRODUCTS = 'SET_SUB_PRODUCTS'

// PRODUCT
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const SET_UPDATE_PRODUCT = 'SET_UPDATE_PRODUCT'
export const SET_SORTED_PRODUCTS = 'SET_SORTED_PRODUCTS'
export const SET_PRODUCT_WITH_DETAILS = 'SET_PRODUCT_WITH_DETAILS'
export const SET_PRODUCT_RATING = 'SET_PRODUCT_RATING'
export const SET_RELATED_PRODUCTS = 'SET_RELATED_PRODUCTS'
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE'
